### ISSUE TITLE
Titanic dataset has been rescaled?

### ISSUE THREAD

**Issue by trangdata** [EpistasisLab/pmlb#21]
It seems that the features in the Titanic dataset [have been rescaled and become continuous](https://github.com/EpistasisLab/penn-ml-benchmarks/tree/ec90219de01b1380dfecc1c735d8216923e43ca0/datasets/classification/titanic). I don't think this is what we want.

**Comment by alexzwanenburg** [comment]
There indeed some issues with this dataset:

- The target (survived) has been transformed to -1.0 and 1.0 values, and should be categorical.
- The *class* feature should be categorical instead of continuous.
- The *sex* feature should be categorical instead of continuous.
- The *age* feature has been rescaled and normalised. Moreover, it seems that *age* and *class* columns were swapped.

It might be best to replace the dataset.  There is a dataset under a CC0 (public domain) license here: https://www.kaggle.com/datasets/aliaamiri/titanic-passengers-and-crew-complete-list. Working from this dataset I propose the following:

- Drop the *name* and *ticketno* columns.
- Most of the missing data in *sibsp* and *parch* columns can be inferred to be 0. These are mostly missing for crew.

To discuss:

- How to handle remaining missing values? Do we encode these as **unknown** or leave **NA** in the file? Or do we drop such instances completely?

**Comment by trangdata** [comment]
Thank you @alexzwanenburg for following up on this issue. 💯  🚀  I like your proposed replacement dataset and suggested changes. PRs are most welcomed!

Regarding missing values, in the python and R package, we have a `dropna` argument (bool) and so I think we should leave NAs in the file and let the user decides.

> Most of the missing data in sibsp and parch columns can be inferred to be 0. These are mostly missing for crew.

If we do encode missing data in these two columns as 0, we want to make sure that we explain so in the metadata.

**Comment by trangdata** [comment]
Addressed in #165
